### ISSUE TITLE
Add support for fish shell

### ISSUE THREAD

**Issue by axeII** [crclark96/ginh#7]
Great and useful script! Though when I tried it it did not work for fish shell :/ 

So I played around and via "quick fixes" I was able to run it on fish shell and there are 2 problems. 

First is that line https://github.com/crclark96/ginh/blob/master/ginh.sh#L62 where variable`$calc` needs awk $3 instead of $1 -- `grep -v -E '^\s*$|^\s+' $histfile | awk '{print $3}' | sort | uniq -c |
    sort -rn` to work with fish history file.

Btw fish history file looks like
```
- cmd: git commit -v -a
  when: 1548438622
- cmd: git push origin master
  when: 1548438636
- cmd: fg
  when: 1548438726
- cmd: head fish_history
  when: 1548438886
  paths:
    - fish_history
```
And second problem is that $PPID doesn't work in fish shell or is empty. Plus line https://github.com/crclark96/ginh/blob/master/ginh.sh#L9 give strange error ` fish: Unknown command 'i'`

That's all for quick report so yeah. This is awesome tool and it would be awesome have it supported by fish shell history logs. So yeah please add support for fish shell 🙏  
Thanks ;) 
ps: quick fixes - https://github.com/L3rchal/ginh/commit/abd35aa364c5482ff9e287627a907bcb78b0e654
